# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:14:44+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity, HTTPBasic
from fastapi import Path, Query
from starlette.requests import Request

from models import (
    ApiV1AutomaticprovisionCreateaccountPostResponse,
    ApiV1AutomaticprovisionTermsinfoGetResponse,
    ApiV1CustomersAddressesIdPatchRequest,
    ApiV1EnumsOrderstatesGetResponse,
    ApiV1EnumsPaymenttypesGetResponse,
    ApiV1EnumsShipmenttypesGetResponse,
    ApiV1EnumsShippingcarriersGetResponse,
    ApiV1EventsGetResponse,
    ApiV1OrdersCreateDeliveryNoteIdPostResponse,
    ApiV1OrdersCreateInvoiceIdPostResponse,
    ApiV1OrdersFindIdPartnerGetResponse,
    ApiV1OrdersIdOrderstatePutResponse,
    ApiV1OrdersIdParsePlaceholdersPostResponse,
    ApiV1OrdersIdPatchRequest,
    ApiV1OrdersIdSendMessagePostResponse,
    ApiV1OrdersIdShipmentPostResponse,
    ApiV1OrdersIdTagsPostResponse,
    ApiV1OrdersIdTagsPutResponse,
    ApiV1OrdersIdTriggerEventPostResponse,
    ApiV1OrdersInvoicesGetResponse,
    ApiV1OrdersPatchableFieldsGetResponse,
    ApiV1ProductsCategoryGetResponse,
    ApiV1ProductsIdDeleteResponse,
    ApiV1ProductsIdPatchRequest,
    ApiV1ProductsIdPatchResponse,
    ApiV1ProductsImagesDeletePostRequest,
    ApiV1ProductsImagesImageIdDeleteResponse,
    ApiV1ProductsPatchableFieldsGetResponse,
    ApiV1ProductsPostResponse,
    ApiV1ProductsProductIdImagesImageIdDeleteResponse,
    ApiV1ProductsProductIdImagesPutRequest,
    ApiV1ProductsUpdatestockmultiplePostRequest,
    ApiV1ProductsUpdatestockmultiplePostResponse,
    ApiV1ShipmentPingGetResponse,
    ApiV1ShipmentShipmentPostResponse,
    ApiV1ShipmentShippingcarriersGetResponse,
    ApiV1ShipmentShippingprovidersGetResponse,
    ApiV1WebhooksDeleteResponse,
    ApiV1WebhooksFiltersGetResponse,
    ApiV1WebhooksGetResponse,
    ApiV1WebhooksIdDeleteResponse,
    ArticleTitleSource,
    BillbeeInterfacesBillbeeAPIModelArticleApiModel,
    BillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel,
    BillbeeInterfacesBillbeeAPIModelCreateCustomerApiModel,
    BillbeeInterfacesBillbeeAPIModelCreateShipmentApiModel,
    BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel,
    BillbeeInterfacesBillbeeAPIModelCustomerApiModel,
    BillbeeInterfacesBillbeeAPIModelOrder,
    BillbeeInterfacesBillbeeAPIModelUpdateStockApiModel,
    BillbeeInterfacesBillbeeAPIModelUpdateStockCodeApiModel,
    OrderStateId,
    RechnungsdruckWebAppControllersApiApiAddShipmentToOrderModel,
    RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel,
    RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleApiModel,
    RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel,
    RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCustomerApiModel,
    RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelOrder,
    RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelShipment,
    RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListRechnungsdruckWebAppControllersApiOrder,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelArticleApiModel,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelCustomerApiModel,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelDeletedImagesModel,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelGetReservedAmountResponseData,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelOrder,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelUpdateStockCodeResponseData,
    RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelUpdateStockResponseData,
    RechnungsdruckWebAppControllersApiApiResultRechnungsdruckWebAppControllersApiSearchControllerSearchResultsModel,
    RechnungsdruckWebAppControllersApiApiResultRechnungsdruckWebAppControllersApiShipmentWithLabelResult,
    RechnungsdruckWebAppControllersApiApiResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel,
    RechnungsdruckWebAppControllersApiApiResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCloudStorageApiModel,
    RechnungsdruckWebAppControllersApiApiResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelsLayoutTemplate,
    RechnungsdruckWebAppControllersApiApiResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelStockResponseData,
    RechnungsdruckWebAppControllersApiAutomaticProvisioningControllerCreateAccountContainer,
    RechnungsdruckWebAppControllersApiOrderApiControllerParseTextContainer,
    RechnungsdruckWebAppControllersApiOrderApiControllerSendMessageModel,
    RechnungsdruckWebAppControllersApiOrderApiControllerTriggerEventContainer,
    RechnungsdruckWebAppControllersApiOrderStateUpdate,
    RechnungsdruckWebAppControllersApiOrderTagCreate,
    RechnungsdruckWebAppControllersApiSearchControllerSearchModel,
    RechnungsdruckWebAppControllersApiShipmentWithLabel,
    RechnungsdruckWebAppControllersApiWebHookApiModel,
    ShopId,
    Tag,
    TypeId,
)

app = MCPProxy(
    contact={
        'email': 'support@billbee.io',
        'name': 'Billbee GmbH',
        'url': 'https://www.billbee.io',
        'x-twitter': 'billbeeio',
    },
    description='Documentation of the Billbee REST API to connect a Billbee account to external aplications.\n\n## Endpoint\n\nThe Billbee API endpoint base url is https://api.billbee.io/api/v1 \n\n## Activation\n\nYou have to enable the API in the settings of your Billbee account. In addition you need a Billbee API Key identifying the application you develop. To get an API key, send a mail to support@billbee.io and send us a short note about what you are building.\n\n## Authorization & security\n\nBecause you can access private data with the Billbee API, every request has to be sent over https and must\n\n* Contain a valid API Key identifying the application/developer. It has to be sent as the HTTP header X-Billbee-Api-Key\n* Contain a valid user login with billbee username and api password in form of a basic auth HTTP header\n\n## Throttling\n\nEach endpoint has a throttle of max 2 requests per second per combination of API Key and Billbee user.\n\nWhen you exceed these 2 calls, the API will return a HTTP 429 status code\n\n',
    title='Billbee API',
    version='v1',
    servers=[{'url': 'https://app.billbee.io'}],
)


@app.post(
    '/api/v1/automaticprovision/createaccount',
    tags=['user_account_management', 'client_data_management'],
)
def automatic_provisioning__create_account(
    body: RechnungsdruckWebAppControllersApiAutomaticProvisioningControllerCreateAccountContainer,
):
    """
    Creates a new Billbee user account with the data passed
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/automaticprovision/termsinfo', tags=['user_account_management'])
def automatic_provisioning__terms_info():
    """
    Returns infos about Billbee terms and conditions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/cloudstorages', tags=['cloud_storage_access'])
def cloud_storage_api__get_list():
    """
    Gets a list of all connected cloud storage devices
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/customer-addresses',
    tags=['client_data_management', 'address_book_management'],
)
def customer_addresses__get_all(
    page: Optional[int] = None, page_size: Optional[int] = Query(None, alias='pageSize')
):
    """
    Get a list of all customer addresses
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/customer-addresses',
    tags=['client_data_management', 'address_book_management'],
)
def customer_addresses__create(
    body: BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel,
):
    """
    Creates a new customer address
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/customer-addresses/{id}',
    tags=['client_data_management', 'address_book_management'],
)
def customer_addresses__get_one(id: int):
    """
    Queries a single customer address by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/customer-addresses/{id}',
    tags=['client_data_management', 'address_book_management'],
)
def customer_addresses__update(
    id: int, body: BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel = ...
):
    """
    Updates a customer address by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/customers',
    tags=['client_data_management', 'search_functionality_operations'],
)
def customer__get_all(
    page: Optional[int] = None, page_size: Optional[int] = Query(None, alias='pageSize')
):
    """
    Get a list of all customers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/customers', tags=['user_account_management', 'client_data_management']
)
def customer__create(body: BillbeeInterfacesBillbeeAPIModelCreateCustomerApiModel):
    """
    Creates a new customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/customers/addresses/{id}',
    tags=['client_data_management', 'address_book_management'],
)
def customer__get_customer_address(id: int):
    """
    Queries a single address from a customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/v1/customers/addresses/{id}',
    description=""" Id and CustomerId cannot be changed """,
    tags=['client_data_management', 'address_book_management'],
)
def customer__patch_address(id: int, body: ApiV1CustomersAddressesIdPatchRequest = ...):
    """
    Updates one or more fields of an address
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/customers/addresses/{id}',
    description=""" Id and CustomerId cannot be changed. Fields you do not send will become empty. """,
    tags=['client_data_management', 'address_book_management'],
)
def customer__update_address(
    id: int, body: BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel = ...
):
    """
    Updates all fields of an address
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/customers/{id}', tags=['client_data_management', 'user_account_management']
)
def customer__get_one(id: int):
    """
    Queries a single customer by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/customers/{id}', tags=['client_data_management', 'user_account_management']
)
def customer__update(
    id: int, body: BillbeeInterfacesBillbeeAPIModelCustomerApiModel = ...
):
    """
    Updates a customer by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/customers/{id}/addresses',
    tags=['client_data_management', 'address_book_management'],
)
def customer__get_customer_addresses(
    id: int,
    page: Optional[int] = None,
    page_size: Optional[int] = Query(None, alias='pageSize'),
):
    """
    Queries a list of addresses from a customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/customers/{id}/addresses',
    description=""" Id and  CustomerId will be ignored in model. If Id is set, the addition will be stopped. """,
    tags=['client_data_management', 'address_book_management'],
)
def customer__add_customer_address(
    id: int, body: BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel = ...
):
    """
    Adds a new address to a customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/customers/{id}/orders', tags=['client_data_management', 'order_processing']
)
def customer__get_customer_orders(
    id: int,
    page: Optional[int] = None,
    page_size: Optional[int] = Query(None, alias='pageSize'),
):
    """
    Queries a list of orders from a customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/enums/orderstates', tags=['enum_order_info', 'order_processing'])
def enum_api__get_order_states():
    """
    Returns a list with all defined orderstates
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/enums/paymenttypes', tags=['enum_order_info'])
def enum_api__get_payment_types():
    """
    Returns a list with all defined paymenttypes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/enums/shipmenttypes',
    tags=['enum_order_info', 'shipment_services_management'],
)
def enum_api__get_shipment_types():
    """
    Returns a list with all defined shipmenttypes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/enums/shippingcarriers',
    tags=['enum_order_info', 'shipment_services_management'],
)
def enum_api__get_shipping_carriers():
    """
    Returns a list with all defined shippingcarriers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/events', tags=['event_retrieval_management'])
def event_api__get_list(
    min_date: Optional[datetime] = Query(None, alias='minDate'),
    max_date: Optional[datetime] = Query(None, alias='maxDate'),
    page: Optional[int] = None,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    type_id: Optional[TypeId] = Query(None, alias='typeId'),
    order_id: Optional[int] = Query(None, alias='orderId'),
):
    """
    Get a list of all events optionally filtered by date. This request is extra throttled to 2 calls per page per hour.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/layouts',
    tags=[
        'user_account_management',
        'client_data_management',
        'order_processing',
        'address_book_management',
        'enum_order_info',
        'event_retrieval_management',
        'cloud_storage_access',
        'layout_settings_management',
        'invoice_handling',
        'shipment_processing',
        'product_inventory_management',
        'inventory_query_management',
        'custom_attributes_management',
        'product_image_operations',
        'article_category_management',
        'product_photo_management',
        'shipment_services_management',
        'search_functionality_operations',
        'webhook_registration_management',
    ],
)
def layout_api__get_list():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/orders', tags=['order_processing', 'search_functionality_operations'])
def order_api__get_list(
    min_order_date: Optional[datetime] = Query(None, alias='minOrderDate'),
    max_order_date: Optional[datetime] = Query(None, alias='maxOrderDate'),
    page: Optional[int] = None,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    shop_id: Optional[ShopId] = Query(None, alias='shopId'),
    order_state_id: Optional[OrderStateId] = Query(None, alias='orderStateId'),
    tag: Optional[Tag] = None,
    minimum_bill_bee_order_id: Optional[int] = Query(
        None, alias='minimumBillBeeOrderId'
    ),
    modified_at_min: Optional[datetime] = Query(None, alias='modifiedAtMin'),
    modified_at_max: Optional[datetime] = Query(None, alias='modifiedAtMax'),
    article_title_source: Optional[ArticleTitleSource] = Query(
        None, alias='articleTitleSource'
    ),
    exclude_tags: Optional[bool] = Query(None, alias='excludeTags'),
):
    """
    Get a list of all orders optionally filtered by date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/orders',
    description=""" To create an order POST an JSON object to the orders endpoint with the shown properties.
Not all properties are required. """,
    tags=['order_processing'],
)
def order_api__post_new_order(
    shop_id: Optional[int] = Query(None, alias='shopId'),
    body: BillbeeInterfacesBillbeeAPIModelOrder = ...,
):
    """
    Creates a new order in the Billbee account
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/v1/orders/CreateDeliveryNote/{id}', tags=['order_processing'])
def order_api__create_delivery_note(
    id: int,
    include_pdf: Optional[bool] = Query(None, alias='includePdf'),
    send_to_cloud_id: Optional[int] = Query(None, alias='sendToCloudId'),
):
    """
    Create an delivery note for an existing order. This request is extra throttled by order and api key to a maximum of 1 per 5 minutes.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/orders/CreateInvoice/{id}', tags=['order_processing', 'invoice_handling']
)
def order_api__create_invoice(
    id: int,
    include_invoice_pdf: Optional[bool] = Query(None, alias='includeInvoicePdf'),
    template_id: Optional[int] = Query(None, alias='templateId'),
    send_to_cloud_id: Optional[int] = Query(None, alias='sendToCloudId'),
):
    """
    Create an invoice for an existing order. This request is extra throttled by order and api key to a maximum of 1 per 5 minutes.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/orders/PatchableFields',
    tags=['order_processing', 'client_data_management'],
)
def order_api__get_patchable_fields():
    """
    Returns a list of fields which can be updated with the orders/{id} patch call
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/orders/find/{id}/{partner}',
    tags=['order_processing', 'search_functionality_operations'],
)
def order_api__find(id: str, partner: str = ...):
    """
    Find a single order by its external id (order number)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/orders/findbyextref/{extRef}', tags=['order_processing'])
def order_api__get_by_ext_ref(ext_ref: str = Path(..., alias='extRef')):
    """
    Get a single order by its external order number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/orders/invoices', tags=['invoice_handling', 'order_processing'])
def order_api__get_invoice_list(
    min_invoice_date: Optional[datetime] = Query(None, alias='minInvoiceDate'),
    max_invoice_date: Optional[datetime] = Query(None, alias='maxInvoiceDate'),
    page: Optional[int] = None,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    shop_id: Optional[ShopId] = Query(None, alias='shopId'),
    order_state_id: Optional[OrderStateId] = Query(None, alias='orderStateId'),
    tag: Optional[Tag] = None,
    min_pay_date: Optional[datetime] = Query(None, alias='minPayDate'),
    max_pay_date: Optional[datetime] = Query(None, alias='maxPayDate'),
    include_positions: Optional[bool] = Query(None, alias='includePositions'),
    exclude_tags: Optional[bool] = Query(None, alias='excludeTags'),
):
    """
    Get a list of all invoices optionally filtered by date. This request ist throttled to 1 per 1 minute for same page and minInvoiceDate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/orders/{id}', tags=['order_processing'])
def order_api__get(
    id: int,
    article_title_source: Optional[ArticleTitleSource] = Query(
        None, alias='articleTitleSource'
    ),
):
    """
    Get a single order by its internal billbee id. This request is throttled to 6 calls per order in one minute
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch('/api/v1/orders/{id}', tags=['order_processing', 'client_data_management'])
def order_api__patch_order(id: int, body: ApiV1OrdersIdPatchRequest = ...):
    """
    Updates one or more fields of an order
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/orders/{id}/orderstate',
    description=""" ### REMARKS ###
Use this call to change the state of an order to i.e. paid or sent.

The state is transfered to the external shop/marketplace if configured.
This is the list of known states:
- 1: ordered
- 2: confirmed
- 3: paid
- 4: shipped
- 5: reclamation
- 6: deleted
- 7: closed
- 8: canceled
- 9: archived
- 10: not used
- 11: demand note 1
- 12: demand note 2
- 13: packed
- 14: offered
- 15: payment reminder
- 16: fulfilling """,
    tags=['order_processing'],
)
def order_api__update_state(
    id: int, body: RechnungsdruckWebAppControllersApiOrderStateUpdate = ...
):
    """
    Changes the main state of a single order
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/orders/{id}/parse-placeholders',
    tags=['invoice_handling', 'order_processing'],
)
def order_api__parse_placeholders(
    id: int,
    body: RechnungsdruckWebAppControllersApiOrderApiControllerParseTextContainer = ...,
):
    """
    Parses a text and replaces all placeholders
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/v1/orders/{id}/send-message', tags=['order_processing'])
def order_api__send_message(
    id: int,
    body: RechnungsdruckWebAppControllersApiOrderApiControllerSendMessageModel = ...,
):
    """
    Sends a message to the buyer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/orders/{id}/shipment', tags=['order_processing', 'shipment_processing']
)
def order_api__add_shipment(
    id: int, body: RechnungsdruckWebAppControllersApiApiAddShipmentToOrderModel = ...
):
    """
    Add a shipment to a given order
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/orders/{id}/tags',
    description=""" When a tag is already attached, it is ignored. Tags are not case sensitive. All given tags are added to the existing tags. """,
    tags=['order_processing'],
)
def order_api__tags_create(
    id: int, body: RechnungsdruckWebAppControllersApiOrderTagCreate = ...
):
    """
    Attach one or more tags to an order
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/orders/{id}/tags',
    description=""" All existing tags will be replaced by the given list of new tags. To just add tags, use POST method. """,
    tags=['order_processing'],
)
def order_api__tags_update(
    id: int, body: RechnungsdruckWebAppControllersApiOrderTagCreate = ...
):
    """
    Sets the tags attached to an order
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/orders/{id}/trigger-event',
    tags=['order_processing', 'event_retrieval_management'],
)
def order_api__trigger_event(
    id: int,
    body: RechnungsdruckWebAppControllersApiOrderApiControllerTriggerEventContainer = ...,
):
    """
    Triggers a rule event
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/products',
    tags=['product_inventory_management', 'search_functionality_operations'],
)
def article__get_list(
    page: Optional[int] = None,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    min_created_at: Optional[datetime] = Query(None, alias='minCreatedAt'),
    minimum_bill_bee_article_id: Optional[int] = Query(
        None, alias='minimumBillBeeArticleId'
    ),
    maximum_bill_bee_article_id: Optional[int] = Query(
        None, alias='maximumBillBeeArticleId'
    ),
):
    """
    Get a list of all products
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/api/v1/products', tags=['product_inventory_management'])
def article__create_article(body: BillbeeInterfacesBillbeeAPIModelArticleApiModel):
    """
    Creates a new product
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/products/PatchableFields',
    tags=['custom_attributes_management', 'client_data_management'],
)
def article__get_patchable_fields():
    """
    Returns a list of fields which can be updated with the patch call
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/products/category', tags=['article_category_management'])
def article__get_category():
    """
    GEts a list of all defined categories
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/products/custom-fields', tags=['custom_attributes_management'])
def article__get_custom_fields(
    page: Optional[int] = None, page_size: Optional[int] = Query(None, alias='pageSize')
):
    """
    Queries a list of all custom fields
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/products/custom-fields/{id}', tags=['custom_attributes_management'])
def article__get_custom_field(id: int):
    """
    Queries a single custom field
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/products/images/delete',
    tags=[
        'product_image_operations',
        'product_photo_management',
        'product_inventory_management',
    ],
)
def article__delete_images(body: ApiV1ProductsImagesDeletePostRequest):
    """
    Delete multiple images by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/products/images/{imageId}',
    tags=['product_image_operations', 'product_photo_management'],
)
def article__delete_image(image_id: int = Path(..., alias='imageId')):
    """
    Deletes a single image by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/products/images/{imageId}',
    tags=['product_image_operations', 'product_photo_management'],
)
def article__get_image(image_id: int = Path(..., alias='imageId')):
    """
    Returns a single image by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/products/reservedamount',
    tags=['inventory_query_management', 'product_inventory_management'],
)
def article__get_reserved_amount(
    id: str,
    lookup_by: Optional[str] = Query(None, alias='lookupBy'),
    stock_id: Optional[int] = Query(None, alias='stockId'),
):
    """
    Queries the reserved amount for a single article by id or by sku
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/products/stocks', tags=['inventory_query_management'])
def article__get_stocks():
    """
    Query all defined stock locations
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/products/updatestock',
    description=""" The article is specified by sku. You have to send the absolute value for the current stock """,
    tags=['product_inventory_management', 'inventory_query_management'],
)
def article__update_stock(body: BillbeeInterfacesBillbeeAPIModelUpdateStockApiModel):
    """
    Update the stock qty of an article
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/products/updatestockcode',
    tags=['product_inventory_management', 'inventory_query_management'],
)
def article__update_stock_code(
    body: BillbeeInterfacesBillbeeAPIModelUpdateStockCodeApiModel,
):
    """
    Update the stock code of an article
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/products/updatestockmultiple',
    tags=['product_inventory_management', 'inventory_query_management'],
)
def article__update_stock_multiple(body: ApiV1ProductsUpdatestockmultiplePostRequest):
    """
    Update the stock qty for multiple articles at once
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/api/v1/products/{id}', tags=['product_inventory_management'])
def article__delete_article(id: int):
    """
    Deletes a product
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/products/{id}',
    tags=['product_inventory_management', 'inventory_query_management'],
)
def article__get_article(
    id: str, lookup_by: Optional[str] = Query(None, alias='lookupBy')
):
    """
    Queries a single article by id or by sku
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/api/v1/products/{id}',
    tags=['product_inventory_management', 'custom_attributes_management'],
)
def article__patch_article(id: int, body: ApiV1ProductsIdPatchRequest = ...):
    """
    Updates one or more fields of a product
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/products/{productId}/images',
    tags=[
        'product_image_operations',
        'product_photo_management',
        'product_inventory_management',
    ],
)
def article__get_images(product_id: int = Path(..., alias='productId')):
    """
    Returns a list of all images of the product
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/products/{productId}/images',
    tags=[
        'product_image_operations',
        'product_photo_management',
        'product_inventory_management',
    ],
)
def article__put_images(
    product_id: int = Path(..., alias='productId'),
    replace: Optional[bool] = None,
    body: ApiV1ProductsProductIdImagesPutRequest = ...,
):
    """
    Add multiple images to a product or replace the product images by the given images
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/v1/products/{productId}/images/{imageId}',
    tags=[
        'product_inventory_management',
        'product_image_operations',
        'product_photo_management',
    ],
)
def article__delete_image_from_product(
    product_id: int = Path(..., alias='productId'),
    image_id: int = Path(..., alias='imageId'),
):
    """
    Deletes a single image from a product
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/products/{productId}/images/{imageId}',
    tags=['product_image_operations', 'product_photo_management'],
)
def article__get_image_from_product(
    product_id: int = Path(..., alias='productId'),
    image_id: int = Path(..., alias='imageId'),
):
    """
    Returns a single image by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/v1/products/{productId}/images/{imageId}',
    tags=[
        'product_inventory_management',
        'product_image_operations',
        'product_photo_management',
    ],
)
def article__put_image(
    product_id: int = Path(..., alias='productId'),
    image_id: int = Path(..., alias='imageId'),
    body: BillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel = ...,
):
    """
    Add or update an existing image of a product
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/search',
    tags=[
        'search_functionality_operations',
        'order_processing',
        'client_data_management',
    ],
)
def search__search(body: RechnungsdruckWebAppControllersApiSearchControllerSearchModel):
    """
        Search for products, customers and orders.
    Type can be "order", "product" and / or "customer"
    Term can contains lucene query syntax
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/shipment/ping')
def shipment__get_ping():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/shipment/shipment',
    tags=['shipment_processing', 'shipment_services_management'],
)
def shipment__post_shipment(
    body: BillbeeInterfacesBillbeeAPIModelCreateShipmentApiModel,
):
    """
    Creates a new shipment with the selected Shippingprovider
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/shipment/shipments',
    tags=['shipment_processing', 'shipment_services_management'],
)
def shipment__get_list(
    page: Optional[int] = None,
    page_size: Optional[int] = Query(None, alias='pageSize'),
    created_at_min: Optional[datetime] = Query(None, alias='createdAtMin'),
    created_at_max: Optional[datetime] = Query(None, alias='createdAtMax'),
    order_id: Optional[int] = Query(None, alias='orderId'),
    minimum_shipment_id: Optional[int] = Query(None, alias='minimumShipmentId'),
    shipping_provider_id: Optional[int] = Query(None, alias='shippingProviderId'),
):
    """
    Get a list of all shipments optionally filtered by date. All parameters are optional.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/shipment/shippingcarriers',
    tags=['enum_order_info', 'shipment_services_management'],
)
def shipment__get_shipping_carrier():
    """
    Queries the currently available shipping carriers.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/shipment/shippingproviders',
    tags=['shipment_services_management', 'enum_order_info'],
)
def shipment__get_shippingproviders():
    """
    Query all defined shipping providers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/shipment/shipwithlabel',
    tags=['shipment_processing', 'shipment_services_management', 'order_processing'],
)
def shipment__ship_with_label(
    body: RechnungsdruckWebAppControllersApiShipmentWithLabel,
):
    """
    Creates a shipment for an order in billbee
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/api/v1/webhooks', tags=['webhook_registration_management'])
def web_hook_management__delete_all():
    """
    Deletes all existing WebHook registrations.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/webhooks', tags=['webhook_registration_management'])
def web_hook_management__get():
    """
    Gets all registered WebHooks for a given user.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/v1/webhooks',
    tags=['webhook_registration_management', 'user_account_management'],
)
def web_hook_management__post(body: RechnungsdruckWebAppControllersApiWebHookApiModel):
    """
    Registers a new WebHook for a given user.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/webhooks/filters', tags=['webhook_registration_management'])
def web_hook_management__get_filters():
    """
    Returns a list of all known filters you can use to register webhooks
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/api/v1/webhooks/{id}', tags=['webhook_registration_management'])
def web_hook_management__delete(id: str):
    """
    Deletes an existing WebHook registration.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/v1/webhooks/{id}', tags=['webhook_registration_management'])
def web_hook_management__lookup(id: str):
    """
    Looks up a registered WebHook with the given {id} for a given user.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/api/v1/webhooks/{id}', tags=['webhook_registration_management'])
def web_hook_management__put(
    id: str, body: RechnungsdruckWebAppControllersApiWebHookApiModel = ...
):
    """
    Updates an existing WebHook registration.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
