# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:14:44+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Type(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class BillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel(BaseModel):
    Configuration: Optional[Dict[str, Any]] = None
    Id: Optional[int] = None
    IsNullable: Optional[bool] = None
    Name: Optional[str] = None
    Type_1: Optional[Type] = Field(None, alias='Type')


class BillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldValueModel(BaseModel):
    ArticleId: Optional[int] = None
    Definition: Optional[
        BillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel
    ] = None
    DefinitionId: Optional[int] = None
    Id: Optional[int] = None
    Value: Optional[Dict[str, Any]] = None


class BillbeeInterfacesBillbeeAPIModelArticleCategoryApiModel(BaseModel):
    Id: Optional[int] = None
    Name: Optional[str] = None


class BillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel(BaseModel):
    ArticleId: Optional[int] = None
    Id: Optional[int] = None
    IsDefault: Optional[bool] = None
    Position: Optional[int] = None
    ThumbPathExt: Optional[str] = None
    ThumbUrl: Optional[str] = None
    Url: Optional[str] = None


class BillbeeInterfacesBillbeeAPIModelArticleSourceApiModel(BaseModel):
    ApiAccountId: Optional[int] = None
    ApiAccountName: Optional[str] = None
    Custom: Optional[Dict[str, Any]] = None
    ExportFactor: Optional[float] = None
    Id: Optional[int] = None
    Source: str
    SourceId: str
    StockSyncInactive: Optional[bool] = None
    StockSyncMax: Optional[float] = None
    StockSyncMin: Optional[float] = None
    UnitsPerItem: Optional[float] = None


class BillbeeInterfacesBillbeeAPIModelBomSubArticleApiModel(BaseModel):
    Amount: Optional[float] = None
    ArticleId: Optional[int] = None
    SKU: Optional[str] = None


class BillbeeInterfacesBillbeeAPIModelCloudStorageApiModel(BaseModel):
    Id: Optional[int] = None
    Name: Optional[str] = None
    Type: Optional[str] = None
    UsedAsPrinter: Optional[bool] = None


class BillbeeInterfacesBillbeeAPIModelCommentApiModel(BaseModel):
    Created: Optional[datetime] = None
    FromCustomer: Optional[bool] = None
    Id: Optional[int] = None
    Name: Optional[str] = None
    Text: Optional[str] = None


class ShippingCarrier(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16
    integer_17 = 17
    integer_18 = 18


class AddressType(Enum):
    integer_1 = 1
    integer_2 = 2


class BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel(BaseModel):
    AddressAddition: Optional[str] = None
    AddressType_1: Optional[AddressType] = Field(
        None, alias='AddressType', description='The type of the address'
    )
    ArchivedAt: Optional[datetime] = Field(
        None,
        description='If set, the customeraddress was already archived at the given date. Further modification is disabled.',
    )
    City: Optional[str] = None
    Company: Optional[str] = Field(None, description='The name of the company')
    CountryCode: Optional[str] = Field(None, description='The ISO2 code of the country')
    CustomerId: Optional[int] = Field(
        None,
        description='The internal Billbee id of the customer the address belongs to',
    )
    Email: Optional[str] = None
    Fax: Optional[str] = None
    FirstName: Optional[str] = None
    Housenumber: Optional[str] = None
    Id: Optional[int] = Field(
        None,
        description='The internal Billbee ID of the address record. Can be null if a new address is created',
    )
    LastName: Optional[str] = None
    Name2: Optional[str] = Field(
        None, description='Optionally an additional name field'
    )
    RestoredAt: Optional[datetime] = Field(
        None,
        description='If set, the customeraddress was restored from the archive at the given date.',
    )
    State: Optional[str] = None
    Street: Optional[str] = None
    Tel1: Optional[str] = None
    Tel2: Optional[str] = None
    Zip: Optional[str] = None


class BillbeeInterfacesBillbeeAPIModelDeletedImagesModel(BaseModel):
    Deleted: Optional[List[int]] = None
    NotFound: Optional[List[int]] = None


class BillbeeInterfacesBillbeeAPIModelGetReservedAmountResponseData(BaseModel):
    ReservedAmount: Optional[float] = Field(
        None, description='The reserve (not fulfilled) qty of the article'
    )


class PaymentMethod(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_6 = 6
    integer_19 = 19
    integer_20 = 20
    integer_21 = 21
    integer_22 = 22
    integer_23 = 23
    integer_24 = 24
    integer_25 = 25
    integer_26 = 26
    integer_27 = 27
    integer_28 = 28
    integer_29 = 29
    integer_30 = 30
    integer_31 = 31
    integer_32 = 32
    integer_33 = 33
    integer_34 = 34
    integer_35 = 35
    integer_36 = 36
    integer_37 = 37
    integer_38 = 38
    integer_39 = 39
    integer_40 = 40
    integer_41 = 41
    integer_42 = 42
    integer_43 = 43
    integer_44 = 44
    integer_45 = 45
    integer_46 = 46
    integer_47 = 47
    integer_48 = 48
    integer_49 = 49
    integer_50 = 50
    integer_51 = 51
    integer_52 = 52
    integer_53 = 53
    integer_54 = 54
    integer_55 = 55
    integer_56 = 56
    integer_57 = 57
    integer_58 = 58
    integer_59 = 59
    integer_60 = 60
    integer_61 = 61
    integer_62 = 62
    integer_63 = 63
    integer_64 = 64
    integer_65 = 65
    integer_66 = 66
    integer_67 = 67
    integer_68 = 68
    integer_69 = 69
    integer_70 = 70
    integer_71 = 71
    integer_72 = 72
    integer_73 = 73
    integer_74 = 74
    integer_75 = 75
    integer_76 = 76
    integer_77 = 77
    integer_78 = 78
    integer_79 = 79
    integer_80 = 80
    integer_81 = 81
    integer_82 = 82
    integer_83 = 83
    integer_84 = 84
    integer_85 = 85
    integer_86 = 86
    integer_87 = 87
    integer_88 = 88
    integer_89 = 89
    integer_90 = 90
    integer_91 = 91
    integer_92 = 92
    integer_93 = 93
    integer_94 = 94
    integer_95 = 95
    integer_96 = 96
    integer_97 = 97
    integer_98 = 98
    integer_99 = 99
    integer_100 = 100
    integer_101 = 101
    integer_102 = 102
    integer_103 = 103
    integer_104 = 104
    integer_105 = 105
    integer_106 = 106
    integer_107 = 107
    integer_108 = 108
    integer_109 = 109
    integer_110 = 110
    integer_111 = 111
    integer_112 = 112
    integer_113 = 113
    integer_114 = 114
    integer_115 = 115
    integer_116 = 116
    integer_117 = 117
    integer_118 = 118
    integer_119 = 119
    integer_120 = 120
    integer_121 = 121
    integer_122 = 122
    integer_123 = 123
    integer_124 = 124
    integer_125 = 125
    integer_126 = 126
    integer_127 = 127
    integer_128 = 128
    integer_129 = 129
    integer_130 = 130
    integer_131 = 131
    integer_132 = 132
    integer_133 = 133
    integer_134 = 134
    integer_135 = 135
    integer_136 = 136


class State(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16


class VatMode(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5


class BillbeeInterfacesBillbeeAPIModelOrderAddressApiModel(BaseModel):
    BillbeeId: Optional[int] = None
    City: Optional[str] = None
    Company: Optional[str] = None
    Country: Optional[str] = None
    CountryISO2: Optional[str] = None
    Email: Optional[str] = None
    FirstName: Optional[str] = None
    HouseNumber: Optional[str] = None
    LastName: Optional[str] = None
    Line2: Optional[str] = None
    NameAddition: Optional[str] = None
    Phone: Optional[str] = None
    State: Optional[str] = None
    Street: Optional[str] = None
    Zip: Optional[str] = None


class BillbeeInterfacesBillbeeAPIModelOrderItemAttribute(BaseModel):
    Id: Optional[str] = Field(None, description='The internal id of this attribute')
    Name: Optional[str] = Field(None, description='The attribute name. E.g. color')
    Price: Optional[float] = None
    Value: Optional[str] = Field(None, description='The attribute value. E.g. red')


class BillbeeInterfacesBillbeeAPIModelOrderUser(BaseModel):
    BillbeeShopId: Optional[int] = Field(
        None, description='The Billbee internal id of the shop connection'
    )
    BillbeeShopName: Optional[str] = Field(
        None, description='The name of shop connection in Billbee'
    )
    Email: Optional[str] = Field(None, description='The email address of this customer')
    FirstName: Optional[str] = Field(
        None, description='The first name of this customer'
    )
    FullName: Optional[str] = Field(
        None, description='The full name ("firstname lastname") of this customer'
    )
    Id: Optional[str] = Field(
        None, description='The Billbee internal id of this customer'
    )
    LastName: Optional[str] = Field(None, description='The last name of this customer')
    Nick: Optional[str] = Field(
        None, description='The nick name (if available) from the original system'
    )
    Platform: Optional[str] = Field(
        None, description='The name of the platform from which this customer originated'
    )


class BillbeeInterfacesBillbeeAPIModelProductImage(BaseModel):
    ExternalId: Optional[str] = Field(
        None, description='The id of this image from the original system'
    )
    IsDefaultImage: Optional[bool] = Field(
        None, description='True if the image is / should be the default image'
    )
    Position: Optional[int] = Field(None, description='The order of this image')
    Url: Optional[str] = Field(None, description='The url to the image')


class BillbeeInterfacesBillbeeAPIModelShipment(BaseModel):
    BillbeeId: Optional[int] = Field(
        None, description='The billbee internal id of the shipment'
    )
    Created: Optional[datetime] = Field(None, description='The creation date')
    ShipmentType: Optional[int] = Field(
        None, description='Shipment Type, 0 if Shipment, 1 if Retoure'
    )
    Shipper: Optional[str] = Field(
        None, description='The name of the shipping provider'
    )
    ShippingCarrier: Optional[int] = Field(
        None, description='The carrier used to ship the parcel with'
    )
    ShippingId: Optional[str] = Field(None, description='The id of this shipment')
    ShippingProviderId: Optional[int] = Field(
        None, description='The id of the used shipping provider'
    )
    ShippingProviderProductId: Optional[int] = Field(
        None, description='The id of the used shipping provider product'
    )
    TrackingUrl: Optional[str] = Field(
        None, description='The url to track this shipment'
    )


class BillbeeInterfacesBillbeeAPIModelShipmentAddressApiModel(BaseModel):
    AddressAddition: Optional[str] = None
    City: Optional[str] = None
    Company: Optional[str] = None
    CountryCode: Optional[str] = None
    CountryCodeISO3: Optional[str] = None
    Email: Optional[str] = None
    FirstName: Optional[str] = None
    FullName: Optional[str] = None
    FullStreet: Optional[str] = None
    Housenumber: Optional[str] = None
    IsExportCountry: Optional[bool] = None
    LastName: Optional[str] = None
    Name2: Optional[str] = None
    State: Optional[str] = None
    Street: Optional[str] = None
    Telephone: Optional[str] = None
    Zip: Optional[str] = None


class BillbeeInterfacesBillbeeAPIModelSoldProduct(BaseModel):
    BillbeeId: Optional[int] = Field(
        None, description='The Billbee internal id of the linked product'
    )
    CountryOfOrigin: Optional[str] = Field(
        None, description='The country where this article was made'
    )
    EAN: Optional[str] = Field(None, description='The EAN / GTIN of this product')
    Id: Optional[str] = Field(
        None, description='The id of this product in the external system'
    )
    Images: Optional[List[BillbeeInterfacesBillbeeAPIModelProductImage]] = Field(
        None, description='The images of this product'
    )
    IsDigital: Optional[bool] = Field(
        None,
        description='True if the product is a digital good (download etc.), false if not',
    )
    OldId: Optional[str] = Field(
        None,
        description='This is for migration scenarios when the internal id of a product changes\r\nI.E. Etsy when switching to the new inventory management, the ids for variants will change.',
    )
    PlatformData: Optional[str] = Field(
        None,
        description='Optional platform specific Data as serialized JSON Object for the product',
    )
    SKU: Optional[str] = Field(None, description='The SKU of this product')
    SkuOrId: Optional[str] = Field(
        None, description='The SKU of this product or the id if the SKU is empty'
    )
    TARICCode: Optional[str] = Field(None, description='The TARIC code')
    Title: Optional[str] = Field(None, description='The name of this product')
    Type: Optional[int] = Field(
        None, description='Indicates whether the article is 1 = normal or 2 = BOM'
    )
    Weight: Optional[int] = Field(None, description='Weight of one item in gram')


class BillbeeInterfacesBillbeeAPIModelStockArticleApiModel(BaseModel):
    Name: Optional[str] = None
    StockCode: Optional[str] = None
    StockCurrent: Optional[float] = None
    StockDesired: Optional[float] = None
    StockId: Optional[int] = None
    StockWarning: Optional[float] = None
    UnfulfilledAmount: Optional[float] = None


class BillbeeInterfacesBillbeeAPIModelStockResponseData(BaseModel):
    Description: Optional[str] = None
    Id: Optional[int] = None
    IsDefault: Optional[bool] = None
    Name: Optional[str] = None


class BillbeeInterfacesBillbeeAPIModelUpdateStockApiModel(BaseModel):
    AutosubtractReservedAmount: Optional[bool] = Field(
        None,
        description='Automatically reduce the NewQuantity by the currently not fulfilled amount',
    )
    BillbeeId: Optional[int] = Field(
        None, description='Optional the ID of the Billbee product to update'
    )
    DeltaQuantity: Optional[float] = Field(
        None, description='This parameter is currently ignored'
    )
    ForceSendStockToShops: Optional[bool] = Field(
        None,
        description='If true, every sent stockchange is stored and transmitted to the connected shop, even if the value has not changed',
    )
    NewQuantity: Optional[float] = Field(
        None,
        description='The new absolute stock quantity for the product you want to set',
    )
    OldQuantity: Optional[float] = Field(
        None, description='This parameter is currently ignored'
    )
    Reason: Optional[str] = Field(
        None, description='Optional a reason text for the stock update'
    )
    Sku: Optional[str] = Field(None, description='The SKU of the product to update')
    StockId: Optional[int] = Field(
        None,
        description='Optional the stock id if the feature multi stock is activated',
    )


class BillbeeInterfacesBillbeeAPIModelUpdateStockCodeApiModel(BaseModel):
    BillbeeId: Optional[int] = None
    Sku: Optional[str] = None
    StockCode: Optional[str] = None
    StockId: Optional[int] = None


class BillbeeInterfacesBillbeeAPIModelUpdateStockCodeResponseData(BaseModel):
    pass


class BillbeeInterfacesBillbeeAPIModelUpdateStockResponseData(BaseModel):
    CurrentStock: Optional[float] = Field(
        None, description='The new value for current stock after the update'
    )
    Message: Optional[str] = Field(
        None,
        description='A human readable message that explains the result of the operation',
    )
    OldStock: Optional[float] = Field(
        None, description='The old value for current stock before the update'
    )
    SKU: Optional[str] = Field(
        None, description='The SKU of the article to update the current stock'
    )
    UnfulfilledAmount: Optional[float] = Field(
        None,
        description='The value of the unfulfilled amount (reserved) of the article',
    )


class BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel(BaseModel):
    Id: Optional[int] = None
    SubType: Optional[str] = None
    TypeId: Optional[int] = None
    TypeName: Optional[str] = None
    Value: Optional[str] = None


class Type1(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5


class BillbeeInterfacesBillbeeAPIModelsLayoutTemplate(BaseModel):
    Id: Optional[int] = None
    Name: Optional[str] = None
    Type: Optional[Type1] = None


class BillbeeInterfacesBillbeeAPIModelsOrderPayment(BaseModel):
    BillbeeId: Optional[int] = None
    Name: Optional[str] = None
    PayDate: Optional[datetime] = None
    PayValue: Optional[float] = None
    PaymentType: Optional[int] = None
    Purpose: Optional[str] = None
    SourceTechnology: Optional[str] = None
    SourceText: Optional[str] = None
    TransactionId: Optional[str] = None


class BillbeeInterfacesOrderHistoryEntry(BaseModel):
    Created: Optional[datetime] = None
    EmployeeName: Optional[str] = None
    EventTypeName: Optional[str] = None
    Text: Optional[str] = None
    TypeId: Optional[int] = None


class BillbeeInterfacesOrderMultiLanguageString(BaseModel):
    LanguageCode: Optional[str] = None
    Text: Optional[str] = None


class BillbeeInterfacesShippingShipmentDataDimensions(BaseModel):
    height: Optional[float] = None
    length: Optional[float] = None
    width: Optional[float] = None


class RechnungsdruckWebAppControllersApiApiAddShipmentToOrderModel(BaseModel):
    CarrierId: Optional[int] = Field(
        None,
        description='Optional the id of a shipping carrier that should be assigend to the shipment\r\nWill override the carrier from the shipment product.\r\nPlease use the integer value from this Enumeration:\r\n{Billbee.Interfaces.Shipping.Enums.ShippingCarrier}',
    )
    Comment: Optional[str] = Field(
        None, description='Optional a text stored with the shipment'
    )
    OrderId: Optional[str] = Field(
        None,
        description='Optional a differing order number of the shipment if available',
    )
    ShipmentType: Optional[int] = Field(
        None,
        description='0 if Shipment, 1 if Retoure\r\n{Billbee.Interfaces.Shipping.Enums.ShipmentTypeEnum}',
    )
    ShippingId: Optional[str] = Field(
        None, description='The id of the shipment (Sendungsnummer/trackingid)'
    )
    ShippingProviderId: Optional[int] = Field(
        None,
        description='Optional the id of a shipping provider existing in the billbee account that should be assigned to the shipment',
    )
    ShippingProviderProductId: Optional[int] = Field(
        None,
        description='Optional the id of a shipping provider product that should be assigend to the shipment',
    )


class RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel(
    BaseModel
):
    Page: Optional[int] = None
    PageSize: Optional[int] = None
    TotalPages: Optional[int] = None
    TotalRows: Optional[int] = None


class RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleApiModel(
    BaseModel
):
    Page: Optional[int] = None
    PageSize: Optional[int] = None
    TotalPages: Optional[int] = None
    TotalRows: Optional[int] = None


class RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel(
    BaseModel
):
    Page: Optional[int] = None
    PageSize: Optional[int] = None
    TotalPages: Optional[int] = None
    TotalRows: Optional[int] = None


class RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCustomerApiModel(
    BaseModel
):
    Page: Optional[int] = None
    PageSize: Optional[int] = None
    TotalPages: Optional[int] = None
    TotalRows: Optional[int] = None


class RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelOrder(
    BaseModel
):
    Page: Optional[int] = None
    PageSize: Optional[int] = None
    TotalPages: Optional[int] = None
    TotalRows: Optional[int] = None


class RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelShipment(
    BaseModel
):
    Page: Optional[int] = None
    PageSize: Optional[int] = None
    TotalPages: Optional[int] = None
    TotalRows: Optional[int] = None


class RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListRechnungsdruckWebAppControllersApiOrder(
    BaseModel
):
    Page: Optional[int] = None
    PageSize: Optional[int] = None
    TotalPages: Optional[int] = None
    TotalRows: Optional[int] = None


class ErrorCode(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16
    integer_17 = 17
    integer_18 = 18
    integer_19 = 19
    integer_20 = 20
    integer_21 = 21
    integer_22 = 22
    integer_23 = 23
    integer_24 = 24
    integer_25 = 25
    integer_26 = 26
    integer_27 = 27
    integer_28 = 28


class ErrorDescription(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16
    integer_17 = 17
    integer_18 = 18
    integer_19 = 19
    integer_20 = 20
    integer_21 = 21
    integer_22 = 22
    integer_23 = 23
    integer_24 = 24
    integer_25 = 25
    integer_26 = 26
    integer_27 = 27
    integer_28 = 28


class RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel(
    BaseModel
):
    Data: Optional[
        List[BillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel]
    ] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None
    Paging: Optional[
        RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel
    ] = None


class RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel(
    BaseModel
):
    Data: Optional[List[BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None
    Paging: Optional[
        RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel
    ] = None


class RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelShipment(
    BaseModel
):
    Data: Optional[List[BillbeeInterfacesBillbeeAPIModelShipment]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None
    Paging: Optional[
        RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelShipment
    ] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel(
    BaseModel
):
    Data: Optional[
        BillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldDefinitionModel
    ] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelDeletedImagesModel(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelDeletedImagesModel] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelGetReservedAmountResponseData(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelGetReservedAmountResponseData] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelUpdateStockCodeResponseData(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelUpdateStockCodeResponseData] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelUpdateStockResponseData(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelUpdateStockResponseData] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel(
    BaseModel
):
    Data: Optional[
        List[BillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel]
    ] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCloudStorageApiModel(
    BaseModel
):
    Data: Optional[List[BillbeeInterfacesBillbeeAPIModelCloudStorageApiModel]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelStockResponseData(
    BaseModel
):
    Data: Optional[List[BillbeeInterfacesBillbeeAPIModelStockResponseData]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelsLayoutTemplate(
    BaseModel
):
    Data: Optional[List[BillbeeInterfacesBillbeeAPIModelsLayoutTemplate]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class DefaultVatMode(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5


class RechnungsdruckWebAppControllersApiAutomaticProvisioningControllerCreateAccountContainerUserAddress(
    BaseModel
):
    Address1: Optional[str] = None
    Address2: Optional[str] = None
    City: Optional[str] = None
    Company: Optional[str] = None
    Country: Optional[str] = Field(
        None, description='The ISO2 country code of the users country'
    )
    Name: Optional[str] = None
    VatId: Optional[str] = None
    Zip: Optional[str] = None


class RechnungsdruckWebAppControllersApiOrder(BaseModel):
    CanCreateAutoInvoice: Optional[bool] = None
    CreatedAt: Optional[datetime] = None
    ExternalId: Optional[str] = None
    HasInvoice: Optional[bool] = None
    Id: Optional[int] = None
    InvoiceCreatedAt: Optional[datetime] = None
    InvoiceDate: Optional[datetime] = None
    InvoiceNumber: Optional[str] = None
    OrderStateId: Optional[int] = None
    OrderStateText: Optional[str] = None
    PaidAt: Optional[datetime] = None
    ShippedAt: Optional[datetime] = None
    ShopName: Optional[str] = None
    TotalGross: Optional[float] = None


class RechnungsdruckWebAppControllersApiOrderApiControllerParseTextContainer(BaseModel):
    IsHtml: Optional[bool] = Field(
        None, description='If true, the string will be handled as html.'
    )
    Language: Optional[str] = Field(
        None,
        description='The ISO 639-1 code of the target language. Using default if not set.',
    )
    TextToParse: Optional[str] = Field(
        None, description='The text to parse and replace the placeholders in.'
    )
    Trim: Optional[bool] = Field(
        None,
        description='If true, then the placeholder values are trimmed after usage.',
    )


class SendMode(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4


class RechnungsdruckWebAppControllersApiOrderApiControllerSendMessageModel(BaseModel):
    AlternativeMail: Optional[str] = None
    Body: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None
    SendMode_1: Optional[SendMode] = Field(None, alias='SendMode')
    Subject: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None


class RechnungsdruckWebAppControllersApiOrderApiControllerTriggerEventContainer(
    BaseModel
):
    DelayInMinutes: Optional[int] = Field(
        None, description='The delay in minutes until the rule is executed'
    )
    Name: Optional[str] = Field(None, description='Name of the event')


class NewStateId(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16


class RechnungsdruckWebAppControllersApiOrderStateUpdate(BaseModel):
    NewStateId_1: Optional[NewStateId] = Field(
        None, alias='NewStateId', description='The new state to set'
    )


class RechnungsdruckWebAppControllersApiOrderTagCreate(BaseModel):
    Tags: Optional[List[str]] = None


class RechnungsdruckWebAppControllersApiSearchControllerCustomerResult(BaseModel):
    Addresses: Optional[str] = None
    Id: Optional[int] = None
    Name: Optional[str] = None
    Number: Optional[str] = None


class RechnungsdruckWebAppControllersApiSearchControllerOrderResult(BaseModel):
    ArticleTexts: Optional[str] = None
    BuyerName: Optional[str] = None
    CustomerName: Optional[str] = None
    ExternalReference: Optional[str] = None
    Id: Optional[int] = None
    InvoiceNumber: Optional[str] = None


class RechnungsdruckWebAppControllersApiSearchControllerProductResult(BaseModel):
    Id: Optional[int] = None
    SKU: Optional[str] = None
    ShortText: Optional[str] = None
    Tags: Optional[str] = None


class SearchMode(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4


class RechnungsdruckWebAppControllersApiSearchControllerSearchModel(BaseModel):
    SearchMode_1: Optional[SearchMode] = Field(None, alias='SearchMode')
    Term: Optional[str] = None
    Type: Optional[List[str]] = None


class RechnungsdruckWebAppControllersApiSearchControllerSearchResultsModel(BaseModel):
    Customers: Optional[
        List[RechnungsdruckWebAppControllersApiSearchControllerCustomerResult]
    ] = None
    Orders: Optional[
        List[RechnungsdruckWebAppControllersApiSearchControllerOrderResult]
    ] = None
    Products: Optional[
        List[RechnungsdruckWebAppControllersApiSearchControllerProductResult]
    ] = None


class RechnungsdruckWebAppControllersApiShipmentWithLabel(BaseModel):
    ChangeStateToSend: Optional[bool] = Field(
        None,
        description='Optional parameter to automatically change the orderstate to sent after creating the shipment',
    )
    ClientReference: Optional[str] = Field(
        None,
        description='Optional specify a reference text to be included on the label. Works not with all carriers',
    )
    Dimension: Optional[BillbeeInterfacesShippingShipmentDataDimensions] = None
    OrderId: Optional[int] = Field(
        None, description='The Billbee internal id of the order to ship'
    )
    PrinterName: Optional[str] = Field(
        None,
        description='Optional the name of a connected cloudprinter to send the label to',
    )
    ProductId: Optional[int] = Field(
        None, description='the id of the shipping provider product to be used'
    )
    ProviderId: Optional[int] = Field(
        None,
        description='The id of the provider. You can query all providers with the shippingproviders endpoint',
    )
    ShipDate: Optional[datetime] = Field(
        None,
        description='Optional specify the shipdate to be transmitted to the carrier',
    )
    WeightInGram: Optional[int] = Field(
        None,
        description='Optional the shipments weight in gram to override the calculated weight',
    )


class RechnungsdruckWebAppControllersApiShipmentWithLabelResult(BaseModel):
    Carrier: Optional[str] = None
    ExportDocsPdf: Optional[str] = None
    LabelDataPdf: Optional[str] = None
    OrderId: Optional[int] = None
    OrderReference: Optional[str] = None
    ShippingDate: Optional[datetime] = None
    ShippingId: Optional[str] = None
    TrackingUrl: Optional[str] = None


class RechnungsdruckWebAppControllersApiWebHookApiModel(BaseModel):
    Description: Optional[str] = None
    Filters: Optional[List[str]] = None
    Headers: Optional[Dict[str, str]] = None
    Id: Optional[str] = None
    IsPaused: Optional[bool] = None
    Properties: Optional[Dict[str, Dict[str, Any]]] = None
    Secret: str
    WebHookUri: str


class SystemCollectionsGenericKeyValuePairSystemInt32SystemString(BaseModel):
    key: Optional[int] = None
    value: Optional[str] = None


class SystemCollectionsGenericKeyValuePairSystemStringSystemCollectionsGenericListSystemCollectionsGenericKeyValuePairSystemInt32SystemString(
    BaseModel
):
    key: Optional[str] = None
    value: Optional[
        List[SystemCollectionsGenericKeyValuePairSystemInt32SystemString]
    ] = None


class ApiV1AutomaticprovisionCreateaccountPostResponse(BaseModel):
    pass


class ApiV1AutomaticprovisionTermsinfoGetResponse(BaseModel):
    pass


class ApiV1CustomersAddressesIdPatchRequest(BaseModel):
    pass


class ApiV1EnumsOrderstatesGetResponse(BaseModel):
    pass


class ApiV1EnumsPaymenttypesGetResponse(BaseModel):
    pass


class ApiV1EnumsShipmenttypesGetResponse(BaseModel):
    pass


class ApiV1EnumsShippingcarriersGetResponse(BaseModel):
    pass


class ApiV1EventsGetResponse(BaseModel):
    pass


class TypeId(RootModel[List[int]]):
    root: List[int]


class ArticleTitleSource(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class ShopId(RootModel[List[int]]):
    root: List[int]


class OrderStateId(RootModel[List[int]]):
    root: List[int]


class Tag(RootModel[List[str]]):
    root: List[str]


class ApiV1OrdersCreateDeliveryNoteIdPostResponse(BaseModel):
    pass


class ApiV1OrdersCreateInvoiceIdPostResponse(BaseModel):
    pass


class ApiV1OrdersPatchableFieldsGetResponse(BaseModel):
    pass


class ApiV1OrdersFindIdPartnerGetResponse(BaseModel):
    pass


class ApiV1OrdersInvoicesGetResponse(BaseModel):
    pass


class ApiV1OrdersIdPatchRequest(BaseModel):
    pass


class ApiV1OrdersIdOrderstatePutResponse(BaseModel):
    pass


class ApiV1OrdersIdParsePlaceholdersPostResponse(BaseModel):
    pass


class ApiV1OrdersIdSendMessagePostResponse(BaseModel):
    pass


class ApiV1OrdersIdShipmentPostResponse(BaseModel):
    pass


class ApiV1OrdersIdTagsPostResponse(BaseModel):
    pass


class ApiV1OrdersIdTagsPutResponse(BaseModel):
    pass


class ApiV1OrdersIdTriggerEventPostResponse(BaseModel):
    pass


class ApiV1ProductsPostResponse(BaseModel):
    pass


class ApiV1ProductsPatchableFieldsGetResponse(BaseModel):
    pass


class ApiV1ProductsCategoryGetResponse(BaseModel):
    pass


class ApiV1ProductsImagesDeletePostRequest(RootModel[List[int]]):
    root: List[int]


class ApiV1ProductsImagesImageIdDeleteResponse(BaseModel):
    pass


class ApiV1ProductsUpdatestockmultiplePostRequest(
    RootModel[List[BillbeeInterfacesBillbeeAPIModelUpdateStockApiModel]]
):
    root: List[BillbeeInterfacesBillbeeAPIModelUpdateStockApiModel]


class ApiV1ProductsUpdatestockmultiplePostResponse(
    RootModel[
        List[
            RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelUpdateStockResponseData
        ]
    ]
):
    root: List[
        RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelUpdateStockResponseData
    ]


class ApiV1ProductsIdDeleteResponse(BaseModel):
    pass


class ApiV1ProductsIdPatchRequest(BaseModel):
    pass


class ApiV1ProductsIdPatchResponse(BaseModel):
    pass


class ApiV1ProductsProductIdImagesPutRequest(
    RootModel[List[BillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel]]
):
    root: List[BillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel]


class ApiV1ProductsProductIdImagesImageIdDeleteResponse(BaseModel):
    pass


class ApiV1ShipmentPingGetResponse(BaseModel):
    pass


class ApiV1ShipmentShipmentPostResponse(BaseModel):
    pass


class ApiV1ShipmentShippingcarriersGetResponse(BaseModel):
    pass


class ApiV1ShipmentShippingprovidersGetResponse(BaseModel):
    pass


class ApiV1WebhooksDeleteResponse(BaseModel):
    pass


class ApiV1WebhooksGetResponse(
    RootModel[List[RechnungsdruckWebAppControllersApiWebHookApiModel]]
):
    root: List[RechnungsdruckWebAppControllersApiWebHookApiModel]


class ApiV1WebhooksFiltersGetResponse(BaseModel):
    pass


class ApiV1WebhooksIdDeleteResponse(BaseModel):
    pass


class BillbeeInterfacesBillbeeAPIModelArticleApiModel(BaseModel):
    BasicAttributes: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None
    BillOfMaterial: Optional[
        List[BillbeeInterfacesBillbeeAPIModelBomSubArticleApiModel]
    ] = None
    Category1: Optional[BillbeeInterfacesBillbeeAPIModelArticleCategoryApiModel] = None
    Category2: Optional[BillbeeInterfacesBillbeeAPIModelArticleCategoryApiModel] = None
    Category3: Optional[BillbeeInterfacesBillbeeAPIModelArticleCategoryApiModel] = None
    Condition: Optional[int] = None
    CostPrice: Optional[float] = None
    CountryOfOrigin: Optional[str] = None
    CustomFields: Optional[
        List[BillbeeInterfacesBillbeeAPIModelArticleApiCustomFieldValueModel]
    ] = None
    DeliveryTime: Optional[int] = None
    Description: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None
    EAN: Optional[str] = None
    ExportDescription: Optional[str] = None
    ExportDescriptionMultiLanguage: Optional[
        List[BillbeeInterfacesOrderMultiLanguageString]
    ] = None
    HeightCm: Optional[float] = None
    Id: Optional[int] = None
    Images: Optional[
        List[BillbeeInterfacesBillbeeAPIModelArticleImageRelationApiModel]
    ] = None
    InvoiceText: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None
    IsCustomizable: bool
    IsDeactivated: Optional[bool] = None
    IsDigital: bool
    LengthCm: Optional[float] = None
    LowStock: Optional[bool] = None
    Manufacturer: Optional[str] = None
    Materials: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None
    Occasion: Optional[int] = None
    Price: float
    Recipient: Optional[int] = None
    SKU: Optional[str] = None
    ShippingProductId: Optional[int] = None
    ShortDescription: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None
    SoldAmount: Optional[float] = None
    SoldAmountLast30Days: Optional[float] = None
    SoldSumGross: Optional[float] = None
    SoldSumGrossLast30Days: Optional[float] = None
    SoldSumNet: Optional[float] = None
    SoldSumNetLast30Days: Optional[float] = None
    Sources: Optional[List[BillbeeInterfacesBillbeeAPIModelArticleSourceApiModel]] = (
        None
    )
    StockCode: Optional[str] = None
    StockCurrent: Optional[float] = None
    StockDesired: Optional[float] = None
    StockReduceItemsPerSale: Optional[float] = None
    StockWarning: Optional[float] = None
    Stocks: Optional[List[BillbeeInterfacesBillbeeAPIModelStockArticleApiModel]] = None
    Tags: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None
    TaricNumber: Optional[str] = None
    Title: Optional[List[BillbeeInterfacesOrderMultiLanguageString]] = None
    Type: int
    Unit: Optional[int] = None
    UnitsPerItem: Optional[float] = None
    Vat1Rate: float
    Vat2Rate: float
    VatIndex: int
    Weight: Optional[int] = None
    WeightNet: Optional[int] = None
    WidthCm: Optional[float] = None


class BillbeeInterfacesBillbeeAPIModelCreateCustomerApiModel(BaseModel):
    Address: Optional[BillbeeInterfacesBillbeeAPIModelCustomerAddressApiModel] = None
    ArchivedAt: Optional[datetime] = Field(
        None,
        description='If set, the customer was already archived at the given date. Further modification is disabled.',
    )
    DefaultCommercialMailAddress: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    DefaultFax: Optional[BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel] = (
        None
    )
    DefaultMailAddress: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    DefaultPhone1: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    DefaultPhone2: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    DefaultStatusUpdatesMailAddress: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    Email: Optional[str] = None
    Id: Optional[int] = Field(None, description='The Billbee Id of the customer')
    LanguageId: Optional[int] = None
    MetaData: Optional[
        List[BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel]
    ] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    PriceGroupId: Optional[int] = None
    RestoredAt: Optional[datetime] = Field(
        None,
        description='If set, the customer was restored from the archive at the given date.',
    )
    Tel1: Optional[str] = None
    Tel2: Optional[str] = None
    Type: Optional[int] = Field(None, description='Customer Type')
    VatId: Optional[str] = Field(
        None,
        description='The vat-id, that should be saved at the customer. Only used if CustomerVatId is not set on the order.',
    )


class BillbeeInterfacesBillbeeAPIModelCustomerApiModel(BaseModel):
    ArchivedAt: Optional[datetime] = Field(
        None,
        description='If set, the customer was already archived at the given date. Further modification is disabled.',
    )
    DefaultCommercialMailAddress: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    DefaultFax: Optional[BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel] = (
        None
    )
    DefaultMailAddress: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    DefaultPhone1: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    DefaultPhone2: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    DefaultStatusUpdatesMailAddress: Optional[
        BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel
    ] = None
    Email: Optional[str] = None
    Id: Optional[int] = Field(None, description='The Billbee Id of the customer')
    LanguageId: Optional[int] = None
    MetaData: Optional[
        List[BillbeeInterfacesBillbeeAPIModelsCustomerMetaDataApiModel]
    ] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    PriceGroupId: Optional[int] = None
    RestoredAt: Optional[datetime] = Field(
        None,
        description='If set, the customer was restored from the archive at the given date.',
    )
    Tel1: Optional[str] = None
    Tel2: Optional[str] = None
    Type: Optional[int] = Field(None, description='Customer Type')
    VatId: Optional[str] = Field(
        None,
        description='The vat-id, that should be saved at the customer. Only used if CustomerVatId is not set on the order.',
    )


class BillbeeInterfacesBillbeeAPIModelOrderItem(BaseModel):
    Attributes: Optional[List[BillbeeInterfacesBillbeeAPIModelOrderItemAttribute]] = (
        Field(None, description='A list of product attributes for this position')
    )
    BillbeeId: Optional[int] = Field(None, description='The billbee id of this item')
    Discount: Optional[float] = Field(None, description='Sets the discount in percent')
    DontAdjustStock: Optional[bool] = Field(
        None,
        description="If true, the import of this order won't adjust the stock level at billbee.",
    )
    GetPriceFromArticleIfAny: Optional[bool] = Field(
        None,
        description='If true, the price will be overwritten by the known article price in billbee if available',
    )
    InvoiceSKU: Optional[str] = Field(
        None,
        description='Contains the SKU from OrderDetail (if available) or from Product',
    )
    IsCoupon: Optional[bool] = Field(
        None,
        description='Determines if it is a coupon, which is interpreted as tax-free payment',
    )
    Product: Optional[BillbeeInterfacesBillbeeAPIModelSoldProduct] = None
    Quantity: Optional[float] = Field(None, description='The sold quantity')
    SerialNumber: Optional[str] = Field(
        None, description='Contains the used serial number'
    )
    ShippingProfileId: Optional[str] = Field(
        None,
        description='Determines if it is a coupon, which is interpreted as tax-free payment',
    )
    TaxAmount: Optional[float] = Field(
        None, description='The tax amount in the total price'
    )
    TaxIndex: Optional[int] = Field(None, description='The tax index.')
    TotalPrice: Optional[float] = Field(
        None, description='The total price (unit price * quantity)'
    )
    TransactionId: Optional[str] = Field(
        None,
        description='Id of the individual transaction. Only required by Ebay to detect aggregated orders',
    )
    UnrebatedTotalPrice: Optional[float] = Field(
        None, description='Is just used for the billbee api'
    )


class BillbeeInterfacesShippingProductService(BaseModel):
    CanBeConfigured: Optional[bool] = None
    DisplayName: Optional[str] = None
    DisplayValue: Optional[str] = None
    PossibleValueLists: Optional[
        List[
            SystemCollectionsGenericKeyValuePairSystemStringSystemCollectionsGenericListSystemCollectionsGenericKeyValuePairSystemInt32SystemString
        ]
    ] = None
    RequiresUserInput: Optional[bool] = None
    ServiceName: Optional[str] = None
    typeName: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleApiModel(
    BaseModel
):
    Data: Optional[List[BillbeeInterfacesBillbeeAPIModelArticleApiModel]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None
    Paging: Optional[
        RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelArticleApiModel
    ] = None


class RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCustomerApiModel(
    BaseModel
):
    Data: Optional[List[BillbeeInterfacesBillbeeAPIModelCustomerApiModel]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None
    Paging: Optional[
        RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelCustomerApiModel
    ] = None


class RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListRechnungsdruckWebAppControllersApiOrder(
    BaseModel
):
    Data: Optional[List[RechnungsdruckWebAppControllersApiOrder]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None
    Paging: Optional[
        RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListRechnungsdruckWebAppControllersApiOrder
    ] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelArticleApiModel(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelArticleApiModel] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelCustomerApiModel(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelCustomerApiModel] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultRechnungsdruckWebAppControllersApiSearchControllerSearchResultsModel(
    BaseModel
):
    Data: Optional[
        RechnungsdruckWebAppControllersApiSearchControllerSearchResultsModel
    ] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiApiResultRechnungsdruckWebAppControllersApiShipmentWithLabelResult(
    BaseModel
):
    Data: Optional[RechnungsdruckWebAppControllersApiShipmentWithLabelResult] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None


class RechnungsdruckWebAppControllersApiAutomaticProvisioningControllerCreateAccountContainer(
    BaseModel
):
    AcceptTerms: Optional[bool] = Field(
        None,
        description='Set to true, if the user has accepted the Billbee terms &amp; conditions',
    )
    Address: Optional[
        RechnungsdruckWebAppControllersApiAutomaticProvisioningControllerCreateAccountContainerUserAddress
    ] = None
    AffiliateCouponCode: Optional[str] = Field(
        None, description='Specifies an billbee affiliate code to attach to the user'
    )
    DefaultCurrrency: Optional[str] = Field(
        None, description='Optionally specify the default currency of the user'
    )
    DefaultVatIndex: Optional[int] = Field(
        None, description='Optionally specify the default vat index of the user'
    )
    DefaultVatMode_1: Optional[DefaultVatMode] = Field(
        None,
        alias='DefaultVatMode',
        description='Optionally specify the default vat mode of the user',
    )
    EMail: str = Field(..., description='The Email address of the user to create')
    Password: Optional[str] = None
    Vat1Rate: Optional[float] = Field(
        None, description='Optionally specify the vat1 (normal) rate of the user'
    )
    Vat2Rate: Optional[float] = Field(
        None, description='Optionally specify the vat2 (reduced) rate of the user'
    )


class BillbeeInterfacesBillbeeAPIModelCreateShipmentApiModel(BaseModel):
    ClientReference: Optional[str] = Field(
        None,
        description='Optional specify a text to be included on the label. Not possible with all carriers',
    )
    Content: Optional[str] = Field(
        None,
        description='Optional specify a text describing the content of the shipment. Used for export shipments',
    )
    CustomerNumber: Optional[str] = Field(None, description='Not used anymore')
    Dimension: Optional[BillbeeInterfacesShippingShipmentDataDimensions] = None
    OrderCurrencyCode: Optional[str] = Field(
        None, description='The Currency if the ordersum'
    )
    OrderSum: Optional[float] = Field(
        None, description='The value of the shipments content'
    )
    PrinterIdForExportDocs: Optional[int] = Field(
        None,
        description='The id of a connected Cloudprinter to sent the export docs to',
    )
    PrinterName: Optional[str] = Field(
        None, description='The name of a connected Cloudprinter to sent the label to'
    )
    ProductCode: Optional[str] = Field(
        None,
        description='The productcode to be used when creating the shipment. Values depends on the carrier used',
    )
    ProviderName: Optional[str] = Field(
        None, description='The name of the provider as specified in the billbee account'
    )
    ReceiverAddress: Optional[
        BillbeeInterfacesBillbeeAPIModelShipmentAddressApiModel
    ] = None
    Services: Optional[List[BillbeeInterfacesShippingProductService]] = Field(
        None, description='A list of services to be used when creating the shipment'
    )
    ShipDate: Optional[datetime] = Field(
        None,
        description='Optional overwrite the shipdate to be transferred to the carrier',
    )
    TotalNet: Optional[float] = Field(
        None, description='The value of the shipments content (net)'
    )
    WeightInGram: Optional[float] = Field(
        None, description='Optional specify the weight in gram of the shipment'
    )
    shippingCarrier: Optional[ShippingCarrier] = None


class BillbeeInterfacesBillbeeAPIModelOrder(BaseModel):
    AcceptLossOfReturnRight: Optional[bool] = Field(
        None, description='Customer accepts loss due to withdrawal'
    )
    AdjustmentCost: Optional[float] = None
    AdjustmentReason: Optional[str] = None
    ApiAccountId: Optional[int] = Field(
        None, description='Id of the account, this order belongs to'
    )
    ApiAccountName: Optional[str] = Field(
        None,
        description='The name of the account, this order belongs to. Will be ignored on order creation.',
    )
    ArchivedAt: Optional[datetime] = Field(
        None,
        description='If set, the order was already archived at the given date. Further modification is disabled.',
    )
    BillBeeOrderId: Optional[int] = Field(
        None, description='The Order.Id from the Billbee database'
    )
    BillBeeParentOrderId: Optional[int] = Field(
        None, description='The Id of the parent order in the Billbee database'
    )
    Buyer: Optional[BillbeeInterfacesBillbeeAPIModelOrderUser] = None
    Comments: Optional[List[BillbeeInterfacesBillbeeAPIModelCommentApiModel]] = Field(
        None, description='All messages / comments of the order'
    )
    ConfirmedAt: Optional[datetime] = Field(
        None, description='The date on which the order was confirmed'
    )
    CreatedAt: Optional[datetime] = Field(
        None, description='The date on which the order was created'
    )
    Currency: Optional[str] = Field(None, description='The three letter currency code.')
    CustomInvoiceNote: Optional[str] = Field(
        None, description='An optional multiline text which is printed on the invoice'
    )
    Customer: Optional[BillbeeInterfacesBillbeeAPIModelCustomerApiModel] = None
    CustomerNumber: Optional[str] = Field(
        None,
        description='The customer number (not to be confused with the id of the customer)',
    )
    CustomerVatId: Optional[str] = Field(
        None,
        description='The vat-id, that was given by the customer to fulfill this order',
    )
    DeliverySourceCountryCode: Optional[str] = Field(
        None,
        description='An optional Country ISO2 Code of the country where order is shipped from (FBA)',
    )
    DistributionCenter: Optional[str] = Field(
        None,
        description='An optional code for the distribution center delivering this order',
    )
    History: Optional[List[BillbeeInterfacesOrderHistoryEntry]] = None
    Id: Optional[str] = Field(
        None, description='Id of the order in the external system (marketplace)'
    )
    InvoiceAddress: Optional[BillbeeInterfacesBillbeeAPIModelOrderAddressApiModel] = (
        None
    )
    InvoiceDate: Optional[datetime] = Field(
        None, description='The date on which the invoice was created'
    )
    InvoiceNumber: Optional[int] = Field(None, description='The invoice number')
    InvoiceNumberPostfix: Optional[str] = Field(
        None, description='The postfix of the invoice number'
    )
    InvoiceNumberPrefix: Optional[str] = Field(
        None, description='The prefix of the invoice number'
    )
    IsCancelationFor: Optional[str] = Field(
        None,
        description='An optional Order Id (externalid) for an order if this is a cancel order (shopify only at the moment)',
    )
    IsFromBillbeeApi: Optional[bool] = Field(
        None,
        description='Indicates whether the order was created through the Billbee-Api or not.',
    )
    LanguageCode: Optional[str] = Field(
        None, description='The two-letter language code of the customer'
    )
    LastModifiedAt: Optional[datetime] = Field(
        None, description='Date of the last update, the order got'
    )
    MerchantVatId: Optional[str] = Field(
        None,
        description='The vat-id, that should be displayed on the invoice and other order documents',
    )
    OrderItems: Optional[List[BillbeeInterfacesBillbeeAPIModelOrderItem]] = Field(
        None, description='The list of items purchased like shirt, pant, toys etc'
    )
    OrderNumber: Optional[str] = Field(
        None,
        description='Order number of the order in the external system (marketplace)',
    )
    PaidAmount: Optional[float] = None
    PayedAt: Optional[datetime] = Field(
        None, description='The date on which the order was paid'
    )
    PaymentInstruction: Optional[str] = Field(
        None,
        description='A textfield optionaly filled with a payment instruction text for printout on the invoice (z.B. Ebay Kauf auf Rechnung)',
    )
    PaymentMethod_1: Optional[PaymentMethod] = Field(
        None, alias='PaymentMethod', description='The payment method'
    )
    PaymentReference: Optional[str] = Field(
        None,
        description="A payment reference. Should not be used any more. Please use 'Payments' instead.",
    )
    PaymentTransactionId: Optional[str] = Field(
        None,
        description="The id of the payment transaction. For example the transaction id of PayPal payment. Should not be used any more. Please use 'Payments' instead.",
    )
    Payments: Optional[List[BillbeeInterfacesBillbeeAPIModelsOrderPayment]] = None
    RebateDifference: Optional[float] = None
    RestoredAt: Optional[datetime] = Field(
        None,
        description='If set, the order was restored from the archive at the given date.',
    )
    Seller: Optional[BillbeeInterfacesBillbeeAPIModelOrderUser] = None
    SellerComment: Optional[str] = Field(None, description='An internal seller comment')
    ShipWeightKg: Optional[float] = Field(
        None, description='The total weight of the shipment(s)'
    )
    ShippedAt: Optional[datetime] = Field(
        None, description='The date on which the order was shipped'
    )
    ShippingAddress: Optional[BillbeeInterfacesBillbeeAPIModelOrderAddressApiModel] = (
        None
    )
    ShippingCost: Optional[float] = Field(None, description='The shipping cost')
    ShippingIds: Optional[List[BillbeeInterfacesBillbeeAPIModelShipment]] = Field(
        None, description='The shipments of the order'
    )
    ShippingProfileId: Optional[str] = Field(
        None, description='Internal Id for the shipping profile for that order'
    )
    ShippingProfileName: Optional[str] = Field(
        None, description='Display Name of Shipping profile, if available'
    )
    ShippingProviderId: Optional[int] = Field(
        None, description='Internal Id for the used shipping provider'
    )
    ShippingProviderName: Optional[str] = Field(
        None, description='The Name for of used shipping provider'
    )
    ShippingProviderProductId: Optional[int] = Field(
        None, description='Internal Id for the used shipping product'
    )
    ShippingProviderProductName: Optional[str] = Field(
        None, description='The Name of the used shipping product'
    )
    ShippingServices: Optional[List[BillbeeInterfacesShippingProductService]] = Field(
        None, description='Additional services for the shipment'
    )
    State_1: Optional[State] = Field(
        None, alias='State', description='The current state of the order'
    )
    Tags: Optional[List[str]] = Field(None, description='The Tags of the order')
    TaxRate1: Optional[float] = Field(None, description='The regular tax rate')
    TaxRate2: Optional[float] = Field(None, description='The reduced tax rate')
    TotalCost: Optional[float] = Field(
        None, description='The total cost excluding shipping cost'
    )
    UpdatedAt: Optional[datetime] = Field(
        None, description='The date on which the order was last updated'
    )
    VatId: Optional[str] = Field(None, description='The customers vat id')
    VatMode_1: Optional[VatMode] = Field(
        None, alias='VatMode', description='The vat mode of the order'
    )


class RechnungsdruckWebAppControllersApiApiPagedResultSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelOrder(
    BaseModel
):
    Data: Optional[List[BillbeeInterfacesBillbeeAPIModelOrder]] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None
    Paging: Optional[
        RechnungsdruckWebAppControllersApiApiPagedResultPagingInformationSystemCollectionsGenericListBillbeeInterfacesBillbeeAPIModelOrder
    ] = None


class RechnungsdruckWebAppControllersApiApiResultBillbeeInterfacesBillbeeAPIModelOrder(
    BaseModel
):
    Data: Optional[BillbeeInterfacesBillbeeAPIModelOrder] = None
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    ErrorDescription_1: Optional[ErrorDescription] = Field(
        None, alias='ErrorDescription'
    )
    ErrorMessage: Optional[str] = None
